"""initial_job_listings_and_pipeline_runs

Revision ID: 342a070bbcde
Revises: 
Create Date: 2026-04-11 03:01:27.783811
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '342a070bbcde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('source', sa.Enum('LINKEDIN', 'WELLFOUND', 'BUILTIN', 'LEVELS_FYI', 'GREENHOUSE', 'LEVER', 'WORKDAY', 'INDEED', 'COMPANY_SITE', 'OTHER', name='jobsource'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'FILTERED_OUT', 'ANALYZING', 'ANALYZED', 'TAILORING', 'PENDING_REVIEW', 'APPROVED', 'APPLYING', 'APPLIED', 'SKIPPED', 'ERRORED', 'INTERVIEW', 'OFFER', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('tailored_resume_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tailored_cover_letter_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_listings_company'), 'job_listings', ['company'], unique=False)
    op.create_index(op.f('ix_job_listings_dedup_key'), 'job_listings', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_job_listings_title'), 'job_listings', ['title'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('pipeline_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='pipelinerunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_pipeline_name'), 'pipeline_runs', ['pipeline_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_pipeline_name'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_job_listings_title'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_dedup_key'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_company'), table_name='job_listings')
    op.drop_table('job_listings')
    # ### end Alembic commands ###
